version: '3.8'

services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: streamwerk_test
      POSTGRES_USER: streamwerk
      POSTGRES_PASSWORD: streamwerk
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U streamwerk -d streamwerk_test"]
      interval: 5s
      timeout: 5s
      retries: 5
