[package]
name = "etl"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = {workspace = true}
tokio = {workspace = true}
tokio-stream = {workspace = true}
anyhow = {workspace = true}
async-stream = {workspace = true}